service: payment-service

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: "ap-south-1"
  memorySize: 512
  timeout: 30
  environment:
    NODE_ENV: ${self:provider.stage}
    JWT_SECRET: ${self:custom.secrets.JWT_SECRET}
    LOG_LEVEL: ${self:custom.logLevel.${sls:stage}, self:custom.logLevel.default}
    RAZORPAY_KEY_ID: ${self:custom.secrets.RAZORPAY_KEY_ID}
    RAZORPAY_KEY_SECRET: ${self:custom.secrets.RAZORPAY_KEY_SECRET}
    RAZORPAY_BASE_URL: ${self:custom.secrets.RAZORPAY_BASE_URL}
    RAZORPAY_WEBHOOK_SECRET: ${self:custom.secrets.RAZORPAY_WEBHOOK_SECRET}
    PAYPAL_CLIENT_ID: ${self:custom.secrets.PAYPAL_CLIENT_ID}
    PAYPAL_CLIENT_SECRET: ${self:custom.secrets.PAYPAL_CLIENT_SECRET}
    PAYPAL_BASE_URL: ${self:custom.secrets.PAYPAL_BASE_URL}
    PAYPAL_CLIENT_ID_SANDBOX: ${self:custom.secrets.PAYPAL_CLIENT_ID_SANDBOX}
    PAYPAL_CLIENT_SECRET_SANDBOX: ${self:custom.secrets.PAYPAL_CLIENT_SECRET_SANDBOX}
    PAYPAL_BASE_URL_SANDBOX: ${self:custom.secrets.PAYPAL_BASE_URL_SANDBOX}
    RAZORPAY_KEY_ID_SANDBOX: ${self:custom.secrets.RAZORPAY_KEY_ID_SANDBOX}
    RAZORPAY_KEY_SECRET_SANDBOX: ${self:custom.secrets.RAZORPAY_KEY_SECRET_SANDBOX}
    RAZORPAY_BASE_URL_SANDBOX: ${self:custom.secrets.RAZORPAY_BASE_URL_SANDBOX}
    RAZORPAY_WEBHOOK_SECRET_SANDBOX: ${self:custom.secrets.RAZORPAY_WEBHOOK_SECRET_SANDBOX}
    SUPABASE_URL: ${self:custom.secrets.SUPABASE_URL}
    SUPABASE_ANON_KEY: ${self:custom.secrets.SUPABASE_ANON_KEY}



  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: '*'
        - Effect: Allow
          Action:
            - dynamodb:BatchGetItem
            - dynamodb:BatchWriteItem
            - dynamodb:PutItem
            - dynamodb:DeleteItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:DescribeTable
          Resource:
            - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.stage}-*
            - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.stage}-*/index/*

plugins:
  - serverless-offline
  - serverless-domain-manager
custom:
  domainName: api.bankstatements2excel.com
  secrets: ${ssm:/aws/reference/secretsmanager/parser-service}
  customDomain:
    domainName: ${self:custom.domainName}
    basePath: ${sls:stage}/payment-service
    stage: $default
    createRoute53Record: false
    endpointType: REGIONAL
    apiType: http
  logLevel:
    prod: INFO
    staging: DEBUG
    dev: DEBUG
    default: DEBUG
functions:
  app:
    handler: dist/index.handler
    events:
      - httpApi:
          path: /
          method: ANY
      - httpApi:
          path: /{proxy+}
          method: ANY

package:
  individually: false
  excludeDevDependencies: true
  patterns:
    - '!**/.git/**'
    - '!**/.gitignore'
    - '!**/README.md'
    - '!**/.env'
    - '!**/.env.*'
    - '!**/.env.example'
    - '!**/nodemon.json'
    - '!**/jest.config.js'
    - '!**/*.test.ts'
    - '!**/*.spec.ts'
    - '!**/coverage/**'
    - '!**/logs/**'