ALTER TABLE jobs ADD COLUMN credits_spent INT NOT NULL DEFAULT 0;
ALTER TABLE jobs ADD COLUMN failure_reason VARCHAR(255) NOT NULL DEFAULT 'UNKNOWN';
ALTER TABLE jobs ADD column download_data JSONB DEFAULT '{}';